// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGb8oDMya8HOiv10mPdOJN0NFckjx1zFQ',
    appId: '1:39376048005:web:aec19ac58ca7cd7a2efeec',
    messagingSenderId: '39376048005',
    projectId: 'todoapp-d7353',
    authDomain: 'todoapp-d7353.firebaseapp.com',
    storageBucket: 'todoapp-d7353.appspot.com',
    measurementId: 'G-VC57WS9R9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKUKEepm8uEJP4005tpz67erlOa6lekvI',
    appId: '1:39376048005:android:05f4b63429affd3b2efeec',
    messagingSenderId: '39376048005',
    projectId: 'todoapp-d7353',
    storageBucket: 'todoapp-d7353.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0OEUC94LigXO0Nvl-kiFCValkxkxbsPc',
    appId: '1:39376048005:ios:53987b1c544d3ab42efeec',
    messagingSenderId: '39376048005',
    projectId: 'todoapp-d7353',
    storageBucket: 'todoapp-d7353.appspot.com',
    iosClientId: '39376048005-k92i7c1c378hmek8q8iug53tt2utbcic.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0OEUC94LigXO0Nvl-kiFCValkxkxbsPc',
    appId: '1:39376048005:ios:ee0a76739e77615c2efeec',
    messagingSenderId: '39376048005',
    projectId: 'todoapp-d7353',
    storageBucket: 'todoapp-d7353.appspot.com',
    iosClientId: '39376048005-ma28b5ji1jr95r61mdd6890nfjqokkgk.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
